from __future__ import annotations

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageDraw, ImageFont

from icdm_plot_style import (
    AMBER,
    AXIS,
    BLUE,
    FIG_WIDTH,
    GRAPHITE,
    GRID,
    RED,
    SPINE,
    TEAL,
    finish_axes,
    panel_label,
    save_figure,
    set_icdm_style,
)


ROOT = Path(__file__).resolve().parents[1]
FIGURES = ROOT / "figures"

COBALT = BLUE


def _set_plot_style() -> None:
    set_icdm_style()


def _finish_axes(ax, *, grid_axis: str = "y") -> None:
    finish_axes(ax, grid_axis=grid_axis)


def _save_figure(fig, stem: str) -> None:
    save_figure(fig, FIGURES / f"{stem}.pdf")


def _font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for raw in [
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/Arial.ttf",
        "C:/Windows/Fonts/calibri.ttf",
    ]:
        path = Path(raw)
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default()


def clean_protocol_schematic() -> None:
    for name in ["icdm_protocol_schematic_final.png", "icdm_protocol_schematic_final-web.png"]:
        path = FIGURES / name
        if not path.exists():
            continue

        img = Image.open(path).convert("RGBA")
        w, h = img.size
        draw = ImageDraw.Draw(img)

        # Remove the defensive bottom-right slogan generated by the image model.
        draw.rounded_rectangle(
            [int(w * 0.755), int(h * 0.820), int(w * 0.995), int(h * 0.995)],
            radius=max(6, int(w * 0.004)),
            fill=(255, 255, 255, 255),
        )

        # Replace one inaccurate sweep label.
        draw.rounded_rectangle(
            [int(w * 0.03), int(h * 0.425), int(w * 0.155), int(h * 0.475)],
            radius=max(6, int(w * 0.004)),
            fill=(255, 255, 255, 255),
        )
        draw.text(
            (int(w * 0.035), int(h * 0.438)),
            "Prototype budget",
            fill=(36, 38, 37, 255),
            font=_font(max(16, int(h * 0.019))),
        )

        out = FIGURES / name.replace("final", "final_clean")
        img.convert("RGB").save(out, quality=95)


def _errorbar(ax, x, y, yerr, label, color, marker="o"):
    ax.errorbar(
        x,
        y,
        yerr=yerr,
        label=label,
        color=color,
        marker=marker,
        linewidth=2.0,
        markersize=5,
        capsize=3,
    )


def same_feature_control_comparison() -> None:
    _set_plot_style()

    methods = [
        "Zero-shot",
        "Proto-only",
        "Diag-G.",
        "Fused map",
        "Score blend",
        "Wrong-class",
    ]
    image = np.array([86.34, 82.05, 69.31, 87.79, 89.68, 59.23])
    fpr = np.array([65.52, 70.45, 74.09, 53.32, 49.61, 87.87])
    colors = [COBALT, "#A9B3B5", "#9A9E9C", "#59AFA8", TEAL, RED]

    fig, axes = plt.subplots(1, 2, figsize=(FIG_WIDTH, 2.45), sharey=True, constrained_layout=True)
    fig.patch.set_facecolor("white")
    y = np.arange(len(methods))

    panels = [
        (axes[0], "A", "Image AUROC", image, "higher is better", (55, 93)),
        (axes[1], "B", "FPR@95TPR", fpr, "lower is better", (45, 92)),
    ]
    for ax, letter, text, values, note, xlim in panels:
        ax.barh(y, values, color=colors, height=0.62)
        ax.set_xlim(*xlim)
        ax.set_xlabel("%")
        ax.set_yticks(y)
        ax.set_yticklabels(methods)
        ax.invert_yaxis()
        _finish_axes(ax, grid_axis="x")
        panel_label(ax, letter, text)
        for yi, val in zip(y, values):
            offset = 0.35 if text.startswith("Image") else 0.45
            ax.text(val + offset, yi, f"{val:.1f}", va="center", ha="left", fontsize=6.8, color=GRAPHITE)
        ax.text(0.02, 0.04, note, transform=ax.transAxes, ha="left", va="bottom", fontsize=6.5, color=AXIS)

    axes[0].axvline(86.34, color=COBALT, linewidth=1.0, linestyle=":")
    axes[1].axvline(65.52, color=COBALT, linewidth=1.0, linestyle=":")
    _save_figure(fig, "icdm_same_feature_controls")


def main_result_comparison() -> None:
    _set_plot_style()

    fig, axes = plt.subplots(2, 2, figsize=(FIG_WIDTH, 3.55), constrained_layout=True)
    fig.patch.set_facecolor("white")

    panels = [
        (
            axes[0, 0],
            "A",
            "MVTec image AUROC",
            ["ZS", "Ours-1", "Ours-2", "Ours-4", "PAD-1", "PAD-2", "PAD-4"],
            [86.34, 89.68, 89.78, 89.89, 92.76, 93.19, 94.08],
            [0, 0.14, 0.20, 0.36, 0.35, 0.43, 1.10],
            (84, 96),
        ),
        (
            axes[0, 1],
            "B",
            "MVTec FPR@95TPR",
            ["ZS", "Ours-1", "Ours-2", "Ours-4", "PAD-1", "PAD-2", "PAD-4"],
            [65.52, 49.61, 51.53, 47.47, 23.22, 21.78, 19.63],
            [0, 0.12, 1.22, 3.33, 3.21, 1.22, 0.69],
            (0, 72),
        ),
        (
            axes[1, 0],
            "C",
            "VisA image AUROC",
            ["ZS", "Ours-1", "Ours-2", "Ours-4", "PAD-1"],
            [73.67, 80.97, 80.72, 80.70, 87.73],
            [0, 0.12, 0.43, 0.24, 0],
            (70, 90),
        ),
        (
            axes[1, 1],
            "D",
            "VisA FPR@95TPR",
            ["ZS", "Ours-1", "Ours-2", "Ours-4", "PAD-1"],
            [79.00, 76.26, 74.77, 77.62, 45.45],
            [0, 0.42, 0.52, 1.04, 0],
            (40, 84),
        ),
    ]

    def color_for(label: str) -> str:
        if label == "ZS":
            return COBALT
        if label.startswith("Ours"):
            return TEAL
        return RED

    for ax, letter, panel_text, labels, values, errs, ylim in panels:
        x = np.arange(len(labels))
        bar_colors = [color_for(label) for label in labels]
        ax.bar(x, values, color=bar_colors, width=0.64)
        ax.errorbar(
            x,
            values,
            yerr=errs,
            fmt="none",
            ecolor=GRAPHITE,
            elinewidth=0.8,
            capsize=2,
            capthick=0.8,
        )
        ax.set_ylim(*ylim)
        ax.set_ylabel("%")
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=30, ha="right")
        _finish_axes(ax, grid_axis="y")
        panel_label(ax, letter, panel_text)
        for xi, val in zip(x, values):
            ax.text(
                xi,
                val + (ylim[1] - ylim[0]) * 0.018,
                f"{val:.1f}",
                ha="center",
                va="bottom",
                fontsize=5.8,
                color=GRAPHITE,
            )

    _save_figure(fig, "icdm_result_comparison")


def metric_transfer_summary() -> None:
    _set_plot_style()
    shots = np.array([0, 1, 2, 4])

    mvtec_img = np.array([86.34, 89.68, 89.78, 89.89])
    mvtec_img_err = np.array([0.0, 0.14, 0.20, 0.36])
    mvtec_fpr = np.array([65.52, 49.61, 51.53, 47.47])
    mvtec_fpr_err = np.array([0.0, 0.12, 1.22, 3.33])
    mvtec_pro = np.array([56.48, 83.40, 83.30, 84.28])
    mvtec_pro_err = np.array([0.0, 1.79, 1.21, 1.71])

    visa_img = np.array([73.67, 80.97, 80.72, 80.70])
    visa_img_err = np.array([0.0, 0.12, 0.43, 0.24])
    visa_fpr = np.array([79.00, 76.26, 74.77, 77.62])
    visa_fpr_err = np.array([0.0, 0.42, 0.52, 1.04])
    visa_pro = np.array([78.66, 81.44, 82.15, 83.55])
    visa_pro_err = np.array([0.0, 1.34, 1.73, 1.78])

    fig, axes = plt.subplots(2, 3, figsize=(FIG_WIDTH, 3.55), sharex=True, constrained_layout=True)
    fig.patch.set_facecolor("white")

    panels = [
        ("A", "MVTec image AUROC", mvtec_img, mvtec_img_err),
        ("B", "MVTec FPR@95TPR", mvtec_fpr, mvtec_fpr_err),
        ("C", "MVTec PRO@200", mvtec_pro, mvtec_pro_err),
        ("D", "VisA image AUROC", visa_img, visa_img_err),
        ("E", "VisA FPR@95TPR", visa_fpr, visa_fpr_err),
        ("F", "VisA PRO@200", visa_pro, visa_pro_err),
    ]

    for ax, (letter, text, y, err) in zip(axes.ravel(), panels):
        color = AMBER if "FPR" in text else TEAL
        _errorbar(ax, shots, y, err, "final rule", color)
        ax.scatter([0], [y[0]], s=35, color=COBALT, zorder=3, label="zero-shot")
        panel_label(ax, letter, text)
        ax.set_xticks(shots)
        ax.set_xticklabels(["ZS", "1", "2", "4"])
        ax.set_ylabel("%")
        _finish_axes(ax)

    axes[1, 0].set_xlabel("support shots")
    axes[1, 1].set_xlabel("support shots")
    axes[1, 2].set_xlabel("support shots")
    _save_figure(fig, "icdm_metric_transfer_summary")


def class_stability_summary() -> None:
    _set_plot_style()
    rows = [
        ("MVTec", 1, 8, 7, 15),
        ("MVTec", 2, 9, 8, 15),
        ("MVTec", 4, 9, 8, 15),
        ("VisA", 1, 7, 4, 12),
        ("VisA", 2, 7, 5, 12),
        ("VisA", 4, 7, 6, 12),
    ]
    labels = [f"{d}\n{shot}-shot" for d, shot, *_ in rows]
    image_pct = [img / total * 100 for _, _, img, _, total in rows]
    fpr_pct = [fpr / total * 100 for _, _, _, fpr, total in rows]
    total_text = [f"/{total}" for *_, total in rows]

    x = np.arange(len(rows))
    width = 0.34

    fig, ax = plt.subplots(figsize=(FIG_WIDTH, 2.25), constrained_layout=True)
    fig.patch.set_facecolor("white")
    ax.bar(x - width / 2, image_pct, width, color=TEAL, label="classes with AUROC gain")
    ax.bar(x + width / 2, fpr_pct, width, color=AMBER, label="classes with FPR reduction")

    for i, (_, _, img, fpr, total) in enumerate(rows):
        ax.text(i - width / 2, image_pct[i] + 2.2, f"{img}/{total}", ha="center", va="bottom", fontsize=7, color=GRAPHITE)
        ax.text(i + width / 2, fpr_pct[i] + 2.2, f"{fpr}/{total}", ha="center", va="bottom", fontsize=7, color=GRAPHITE)

    ax.axhline(50, color="#D8D3C7", linewidth=0.9, linestyle="--")
    ax.set_ylim(0, 105)
    ax.set_ylabel("class share (%)")
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    panel_label(ax, "A", "class-level stability")
    _finish_axes(ax)
    ax.legend(loc="upper left", ncols=2, frameon=False)

    _save_figure(fig, "icdm_class_stability_summary")


def per_class_delta_strip() -> None:
    _set_plot_style()
    sources = [
        ("MVTec", ROOT / "runs" / "failure_analysis" / "mvtec_final512_per_class.csv"),
        ("VisA", ROOT / "runs" / "failure_analysis" / "visa_full_per_class.csv"),
    ]
    fig, axes = plt.subplots(1, 2, figsize=(FIG_WIDTH, 2.65), sharey=False, constrained_layout=True)
    fig.patch.set_facecolor("white")

    for letter, ax, (dataset, path) in zip(["A", "B"], axes, sources):
        data = []
        with path.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                if row["shot"] == "1":
                    data.append(
                        (
                            row["class_name"],
                            float(row["delta_image_auroc_mean"]) * 100,
                            float(row["delta_normal_fpr_at_95_tpr_mean"]) * 100,
                        )
                    )
        data.sort(key=lambda item: item[2])
        y = np.arange(len(data))
        fpr_delta = [item[2] for item in data]
        colors = [TEAL if v < 0 else RED for v in fpr_delta]
        ax.barh(y, fpr_delta, color=colors, alpha=0.9)
        ax.axvline(0, color=GRAPHITE, linewidth=0.8)
        ax.set_yticks(y)
        ax.set_yticklabels([item[0].replace("_", " ") for item in data], fontsize=6)
        panel_label(ax, letter, f"{dataset} 1-shot FPR delta")
        ax.set_xlabel("percentage points vs zero-shot")
        _finish_axes(ax, grid_axis="x")

    axes[0].text(0.01, 0.02, "left is better", transform=axes[0].transAxes, fontsize=6.5, color=AXIS)
    _save_figure(fig, "icdm_per_class_fpr_delta_strip")


def main() -> None:
    clean_protocol_schematic()
    same_feature_control_comparison()
    main_result_comparison()
    metric_transfer_summary()
    class_stability_summary()
    per_class_delta_strip()


if __name__ == "__main__":
    main()
